# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13honQNHth06kHCLAvLtFGC7CnIoHHkk4
"""

import pandas as pd

df = pd.read_csv("Student_Performance.csv")

df.head()

df.describe()

df.isnull().sum()

df['Extracurricular Activities'].replace({'Yes': 1, 'No': 0}, inplace=True)

from sklearn.linear_model import LinearRegression

x = df.drop('Performance Index', axis=1)
y = df['Performance Index']

model = LinearRegression()

model.fit(x,y)

model.predict([pred])

pred = [7,99,1,9,1]

